name: Cloud Functions

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

concurrency: ${{ github.ref }}

env:
  FUNCTION_NAME: redgifs-notification-${{ github.ref_name }}
  GCP_SA: integration-1@sturdy-actor-357410.iam.gserviceaccount.com
  ENV_FILE: env.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}" >> ${{ env.ENV_FILE }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - run: npm ci

      - run: tsc --project tsconfig.build.json

      - run: |
          cp package.json dist/package.json
          cp package-lock.json dist/package-lock.json

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v0

      - run: >-
          gcloud functions deploy ${{ env.FUNCTION_NAME }}
          --entry-point=main
          --source=dist
          --region=us-central1
          --timeout=120
          --memory=512MB
          --runtime=nodejs16
          --trigger-http
          --no-user-output-enabled
          --service-account=${{ env.GCP_SA }}
          --env-vars-file=${{ env.ENV_FILE }}
          --allow-unauthenticated
